In [9]:
import pandas as pd 

employee = {
    "name": ["Ronak","Neha","Amit"],
    "salary":[50000,30000,80000],
    "department":["IT","HR","Account"]
}

df = pd.DataFrame(employee)

print(df)

    name  salary department
0  Ronak   50000         IT
1   Neha   30000         HR
2   Amit   80000    Account

In [10]:
df.head()

    name  salary department
0  Ronak   50000         IT
1   Neha   30000         HR
2   Amit   80000    Account

In [11]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        3 non-null      str
 1   salary      3 non-null      int64
 2   department  3 non-null      str
dtypes: int64(1), str(2)
memory usage: 204.0 bytes

In [12]:
df.describe()

             salary
count      3.000000
mean   53333.333333
std    25166.114784
min    30000.000000
25%    40000.000000
50%    50000.000000
75%    65000.000000
max    80000.000000

In [17]:
data = {
    "iteam":["Laptop","Mouse","Keyboard"],
    "price":[50000,500,800],
    "qty":[2,3,5]
}

result = pd.DataFrame(data)

print(result[:2])
result.info()
result.describe()

    iteam  price  qty
0  Laptop  50000    2
1   Mouse    500    3
<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   iteam   3 non-null      str
 1   price   3 non-null      int64
 2   qty     3 non-null      int64
dtypes: int64(2), str(1)
memory usage: 204.0 bytes

              price       qty
count      3.000000  3.000000
mean   17100.000000  3.333333
std    28492.630626  1.527525
min      500.000000  2.000000
25%      650.000000  2.500000
50%      800.000000  3.000000
75%    25400.000000  4.000000
max    50000.000000  5.000000

In [18]:
print(result[["iteam","qty"]])

      iteam  qty
0    Laptop    2
1     Mouse    3
2  Keyboard    5

In [ ]:
## Exercise 3
employees = {
"name":["Ronak","Amit","Neha","Raj"],

"salary":[50000,80000,30000,90000],

"dept":["SQL","Python","SQL","Python"]
}

result = pd.DataFrame(employees)

output = result[
    (result["salary"]>70000)
    |
    (result["dept"]=="Python")
]

print(output)

   name  salary    dept
1  Amit   80000  Python
3   Raj   90000  Python

In [26]:
result["annual_salary"] = (
    result["salary"] * 12
)

print(result)

    name  salary    dept  annual_salary
0  Ronak   50000     SQL         600000
1   Amit   80000  Python         960000
2   Neha   30000     SQL         360000
3    Raj   90000  Python        1080000

In [27]:
result.rename(
    columns={
        "name":"employee_name"
    },
    inplace=True
)

print(result)

  employee_name  salary    dept  annual_salary
0         Ronak   50000     SQL         600000
1          Amit   80000  Python         960000
2          Neha   30000     SQL         360000
3           Raj   90000  Python        1080000

In [ ]:
result.sort_values(
    "salary",
    ascending=False
)

  employee_name  salary    dept  annual_salary
3           Raj   90000  Python        1080000
1          Amit   80000  Python         960000
0         Ronak   50000     SQL         600000
2          Neha   30000     SQL         360000

In [71]:
import numpy as np

employees = {
"name":["Ronak","Amit","Neha","Raj"],

"salary":[50000,80000,30000,90000],

"dept":["SQL","Python","SQL","Python"]
}

emp = pd.DataFrame(employees)

emp["annual_salary"] = (emp["salary"] * 12)

emp["grade"] = np.where(emp["salary"]>=70000,"Senior","Junior")

Senior_emp = emp[emp["grade"]=="Senior"]
print(Senior_emp)

emp.sort_values(
    "salary",
    ascending=False
)

   name  salary    dept  annual_salary   grade
1  Amit   80000  Python         960000  Senior
3   Raj   90000  Python        1080000  Senior

    name  salary    dept  annual_salary   grade
3    Raj   90000  Python        1080000  Senior
1   Amit   80000  Python         960000  Senior
0  Ronak   50000     SQL         600000  Junior
2   Neha   30000     SQL         360000  Junior